### ISSUE TITLE
Crash IOS

### ISSUE THREAD

**Issue by Adnan-addi** [MohsinN/sellcast-issues#12] opened 2018-01-01 10:08 UTC
App Crashed when Select Video-> Bidcast -> Category Cars and hit next -->IOS

**Comment by sarmadmakhdoom** [comment] 2018-01-01 12:16
did you enter the information for car or not? Because I am not able to reproduce it. Can you reproduce it on your end again?

**Comment by sarmadmakhdoom** [comment] 2018-01-01 12:46
Still could not reproduce it. And I did not get any crash report as well. So keeping it open until I found something

**Comment by sarmadmakhdoom** [comment] 2018-01-03 10:32
Closing this issue for now until we receive this crash again as I am not able to reproduce it at all.

**Closed as completed by sarmadmakhdoom** 2018-01-03 10:32 UTC
